baseURL = "https://example.com"

theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yml"
publishDir = "docs"

# enableMissingTranslationPlaceholders = false
defaultContentLanguage = 'jp'
defaultContentLanguageInSubdir = true

[languages]
  [languages.jp]
    disabled = false
    languageCode = 'jp-JP'
    languageDirection = 'ltr'
    languageName = 'Japanese'
    title = 'Kakip 技術ドキュメント'
    weight = 1
    [languages.jp.params]
      subtitle = 'リファレンス、チュートリアルと説明'
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Kakip Techdoc'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

[params]

    # Source Code repository section
    # description = "put your description"
    description = "Welcome Kakip World!"
    # github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    github_repository = "https://github.com/mtutimoti/kakip_techdoc.git"
    version = "0.0.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    # github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    # github_doc_repository_path = ""
    # github_doc_repository_branch = "master"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
  [[menu.main]]
      identifier = "language"
      name = "language"
      url = "/"
      weight = 1
      pre = "<i class='fa fa-home'></i>&nbsp;"
  [[menu.main]]
      identifier = "Japanese"
      name = "Japanese"
      url = "/jp"
      parent = "language"
      weight = 1
  [[menu.main]]
      identifier = "English"
      name = "English"
      url = "/en"
      parent = "language"
      weight = 2
  [[menu.main]]
      name = ""
      url = "https://x.com/kakip_yds"
      weight = 2
      identifier = 'twitter'
      pre = "<b>X</b>"
      post = " @kakip_yds"
      [menu.main.params]
        class = 'twitter-menu-item'

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
